### ISSUE TITLE
Input Url is invalid

### ISSUE THREAD

**Issue by repomani** [abinj30/pricefinder-ecommerce#11]
Hi

I am getting the error input url is invalid for product:

https://www.amazon.de/dp/B07X8ZLYLR

What's the problem?

**Comment by abinj30** [comment]
@ymachupicchuy 
The module is created for Amazon.in and Flipkart.com. Amazon.de is not currently supported.

**Comment by repomani** [comment]
Hi,

Thanks for your response.

I changed the url to german Amazon but is it possible to know which selector I need to choose for the German site or does it not work for the german site? I tried with  priceblock_vat_inc_price

But getting NAN

**Comment by abinj30** [comment]
It works for the https://www.amazon.de/dp/B07X8ZLYLR. You just need to add the below line config.js file line 16

`/http[s]*:[\/]{2}www\.amazon\.de\/dp\/.{10}/i`

**Comment by repomani** [comment]
Here are my setting but still gettin NAN

```
  amazon: {
      urlPatterns: [
         /http[s]*:[\/]{2}www\.amazon\.de\/gp\/product\/.{10}/i,
         /http[s]*:[\/]{2}www\.amazon\.de\/dp\/.{10}/i,
         /http[s]*:[\/]{2}www\.amazon\.de\/.*\/dp\/.{10}/i,
         /http[s]*:[\/]{2}www\.amazon\.de\/dp\/.{10}/i
      ],
      productCodeLength: 10,
      priceReplRegex: /€| |,/gi,
      priceSelectors: [".priceblock_vat_inc_price","#priceblock_ourprice", "#priceblock_dealprice", "#priceblock_saleprice"
      ],
      nameSelector: "#productTitle",
      availabilitySelector: "#availability",
      notAvailableStr: "Currently unavailable"
   }
```

**Comment by abinj30** [comment]
There are no changes required in the selector. Just adding the regex for amazon.de is enough. I've made the changes for the same in [amazon.de branch](https://github.com/abinj30/pricefinder-ecommerce/compare/amazon.de) . Please check and test it with more products.
```
const pricefinder = require("./index");
(async function () {
   var product = await pricefinder("https://www.amazon.de/dp/B07X8ZLYLR", "amazon");
   console.log(product);
})();

{
  productCode: 'B07X8ZLYLR',
  name: 'Anker PowerExpand+ 5-in-1 USB-C Ethernet Hub, Adapter mit 4K USB-C auf HDMI, Ethernet-Eingang, 3 USB 3.0 Ports, für MacBook Pro, iPad Pro, XPS, Pixelbook, und mehr',
  price: 3822,
  available: true,
  url: 'https://www.amazon.de/dp/B07X8ZLYLR'
}
```

**Comment by repomani** [comment]
Hi, Many thanks for your help. I appreciate. 
It works but not 100%. 
I am getting NAN for following product:
 https://www.amazon.de/dp/B003D0YN9I

**Comment by abinj30** [comment]
Are you sure? I'm getting the expected outputs:

```
{
  productCode: 'B003D0YN9I',
  name: 'Caykur Rize Turist - Türkischer Tee (500g)',
  price: 880,
  available: true,
  url: 'https://www.amazon.de/dp/B003D0YN9I'
}
```
